version: '3'

services:
  pg:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - ../postgres_to_es/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 5

  es:
    image: elasticsearch:8.6.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test:     
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build:
      context: ../postgres_to_es
      dockerfile: Dockerfile
    depends_on:
      pg:
        condition: service_healthy
      es:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    env_file:
      - ../postgres_to_es/.env

volumes:
  postgres_data:
    external: true
  elasticsearch_data:
  redis_data: